# Generated by Django 3.1.1 on 2020-09-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200920_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='username',
            new_name='user',
        ),
    ]
