# Generated by Django 2.1.1 on 2020-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validationString',
            field=models.TextField(blank=True, null=True),
        ),
    ]
